Cleanup monitoring docs
ObolNetwork/obol-docs pull request #236
Opened 2023-07-25 09:32 UTC by haroldsphinx

- cleanuo contents

2023-07-25 11:11 UTC, maeliosakyne requested changes

2023-07-25 11:11 UTC, maeliosakyne commented on docs/int/quickstart/monitoring.md
> +11. PeerPingLatency: 1. This alert is activated if the 90th percentile of the ping latency to the peers in a cluster exceeds 500ms within 2 minutes.
Should there be quotation marks around PeerPingLatency?

2023-07-31 08:53 UTC, thomasheremans commented
Hey @haroldsphinx, could you add the recommendations shared over Slack as well? Thanks

2023-08-17 09:14 UTC, maeliosakyne approved these changes

2023-08-17 09:14 UTC, thomasheremans approved these changes

2023-08-17 09:15 UTC, merged