fix: serious grammar and spelling errors in docs
ObolNetwork/obol-docs pull request #431
Opened 2024-10-15 17:13 UTC by antews

## Summary

In reviewing the project documentation, I have identified and corrected several errors and typos that were inadvertently made during its creation. These errors can lead to confusion or misunderstanding. 

## Details

Ensuring clarity and accuracy in documentation is critical for both users and developers. 

Closes #432 

ticket:
#432

2024-10-28 17:53 UTC, OisinKyne commented on docs/advanced/quickstart-builder-api.mdx
> +You should check that your validator client's logs look healthy, and ensure that you haven't added a `fee-recipient` address that conflicts with what has been selected by your cluster in your `cluste
```suggestion
You should check that your validator client's logs look healthy, and ensure that you haven't added a `fee-recipient` address that conflicts with what has been selected by your cluster in your `cluster-lock.json` file, as that may prevent your validator from producing a signature for the block when the opportunity arises. You should also confirm the same for all of the other peers in your cluster.
```

2024-10-28 17:53 UTC, OisinKyne commented on docs/advanced/quickstart-builder-api.mdx
> +This indicates that your Charon node is successfully registering with the relay for a blind block when the time comes.
```suggestion
This indicates that your Charon node is successfully registering with the relay for a blinded block when the time comes.
```
They are called blinded blocks. https://ethereum.github.io/beacon-APIs/#/Validator/produceBlindedBlock

2024-10-28 17:54 UTC, OisinKyne approved these changes

2024-10-28 18:01 UTC, OisinKyne commented
Hey i can't merge this due to conflicts, can you figure out does it need a rebase or what is up with it? :)

2024-10-28 18:24 UTC, OisinKyne reviewed
Needs rebase

2024-10-28 18:24 UTC, OisinKyne requested changes
Needs rebase

2024-10-29 12:06 UTC, antews commented
> Hey i can't merge this due to conflicts, can you figure out does it need a rebase or what is up with it? :)

Hi! @OisinKyne I've rebased and resolved all conflicts, now PR is ready for merge! Thanks!

2024-10-29 12:07 UTC, antews commented
> Hi! @OisinKyne I've rebased and resolved all conflicts, now PR is ready for merge! Thanks!

Hi! @OisinKyne  I've rebased and resolved all conflicts, now PR is ready for merge! Thanks!

2024-10-29 14:56 UTC, OisinKyne commented
Hey apologies. I was in a hurry to get these changes in before I tagged the next release such that they would show up outside the `next` section, so i implemented them in another PR. This PR just has two extra newlines left. Appreciate the follow up and rebase though, sorry for not coming back to this!

2024-10-29 14:56 UTC, closed without merging

2024-10-29 15:07 UTC, antews commented
> Hey apologies. I was in a hurry to get these changes in before I tagged the next release such that they would show up outside the `next` section, so i implemented them in another PR. This PR just has two extra newlines left. Appreciate the follow up and rebase though, sorry for not coming back to this!

Now I'am won't be in the contributor list, right? @OisinKyne

2024-10-30 22:47 UTC, antews commented
> Hey apologies. I was in a hurry to get these changes in before I tagged the next release such that they would show up outside the `next` section, so i implemented them in another PR. This PR just has two extra newlines left. Appreciate the follow up and rebase though, sorry for not coming back to this!

?

2024-10-31 09:02 UTC, slugmann321 commented
@antews please only contribute if you actually want to see changes, not to get on a list. There is no "list" and being a contributor will not advantage you in any way. Thank you.